import uranus
#agent=uranus.Uranus(cfgfn='config.poseidon.d01.wanda.ini')
#agent=uranus.Uranus(cfgfn='config.poseidon.d01.mangkhut.noluzon.ini')
#agent=uranus.Uranus(cfgfn='config.poseidon.d02.ini')
#agent=uranus.Uranus(cfgfn='config.poseidon.d02.mangkhut.ini')
agent=uranus.Uranus(cfgfn='config.poseidon.d03.mangkhut.restart.ini')
#agent=uranus.Uranus(cfgfn='poseidon_L30.ini')
#agent=uranus.Uranus(cfgfn='les_aqua.ini')
#agent=uranus.Uranus(cfgfn='les_aqua.restart.ini')
#agent=uranus.Uranus(cfgfn='config.poseidon.d03.mangkhut.ini')
#agent=uranus.Uranus(cfgfn='config.poseidon.d03.ini')
agent.waterfall()
